# Generated by Django 5.2 on 2025-04-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CADSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('developer', models.CharField(max_length=100)),
                ('short_info', models.CharField(blank=True, max_length=200, null=True)),
                ('full_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('release_date', models.DateField()),
                ('license_type', models.CharField(choices=[('subscription', 'Подписка'), ('permanent', 'Постоянная'), ('free', 'Бесплатная')], default='subscription', max_length=20)),
                ('is_russian', models.BooleanField(default=False)),
                ('system_type', models.CharField(choices=[('CAD', 'CAD'), ('CAE', 'CAE'), ('CAM', 'CAM'), ('PLM', 'PLM')], default='CAD', max_length=20)),
                ('platforms', models.CharField(blank=True, max_length=100, null=True)),
                ('file_formats', models.CharField(blank=True, max_length=100, null=True)),
                ('advantages', models.TextField(blank=True, null=True)),
                ('disadvantages', models.TextField(blank=True, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('official_url', models.URLField(blank=True, null=True)),
                ('demo_url', models.URLField(blank=True, null=True)),
                ('docs_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cad_images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('features', models.ManyToManyField(blank=True, to='myapp.feature')),
            ],
        ),
    ]
