# Generated by Django 5.2 on 2025-04-26 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='bi-pc-display', max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(choices=[('primary', 'Синий (primary)'), ('secondary', 'Серый (secondary)'), ('success', 'Зеленый (success)'), ('danger', 'Красный (danger)'), ('warning', 'Желтый (warning)'), ('info', 'Голубой (info)'), ('dark', 'Темный (dark)')], default='primary', max_length=20, verbose_name='Цвет')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL-адрес')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название характеристики')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='CADSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('developer', models.CharField(max_length=100, verbose_name='Разработчик')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('short_info', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('image', models.ImageField(blank=True, help_text='Рекомендуемый размер: 300x300px', upload_to='sapr_images/', verbose_name='Логотип')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='sapr_screenshots/', verbose_name='Скриншот интерфейса')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена')),
                ('license_type', models.CharField(choices=[('permanent', 'Постоянная лицензия'), ('subscription', 'Подписка'), ('free', 'Бесплатная'), ('trial', 'Пробная версия')], default='subscription', max_length=12, verbose_name='Тип лицензии')),
                ('is_russian', models.BooleanField(default=False, verbose_name='Российское ПО')),
                ('system_type', models.CharField(choices=[('CAD', 'Система проектирования'), ('CAM', 'Система производства'), ('CAE', 'Инженерный анализ'), ('BIM', 'Информационное моделирование зданий'), ('PLM', 'Управление жизненным циклом')], default='CAD', max_length=3, verbose_name='Тип системы')),
                ('platforms', models.CharField(blank=True, help_text='Например: Windows, Linux, macOS', max_length=100, verbose_name='Платформы')),
                ('file_formats', models.CharField(blank=True, max_length=200, verbose_name='Поддерживаемые форматы')),
                ('advantages', models.TextField(blank=True, verbose_name='Преимущества')),
                ('disadvantages', models.TextField(blank=True, verbose_name='Недостатки')),
                ('rating', models.FloatField(default=0.0, help_text='От 0 до 5', verbose_name='Рейтинг')),
                ('official_url', models.URLField(verbose_name='Официальный сайт')),
                ('demo_url', models.URLField(blank=True, verbose_name='Ссылка на демо-версию')),
                ('docs_url', models.URLField(blank=True, verbose_name='Ссылка на документацию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='myapp.category', verbose_name='Категория')),
                ('features', models.ManyToManyField(blank=True, to='myapp.feature', verbose_name='Характеристики')),
            ],
            options={
                'verbose_name': 'Система САПР',
                'verbose_name_plural': 'Системы САПР',
                'ordering': ['category__name', 'name'],
                'unique_together': {('name', 'developer')},
            },
        ),
    ]
