# Generated by Django 5.2 on 2025-04-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadsystem',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Система САПР', 'verbose_name_plural': 'Системы САПР'},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ['name'], 'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
        migrations.AddField(
            model_name='feature',
            name='icon',
            field=models.CharField(blank=True, help_text="Иконка из Bootstrap Icons (например, 'bi-check')", max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='bi-pc-display', help_text="Иконка из Bootstrap Icons (например, 'bi-gear')", max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text="ЧПУ для URL (например, 'graphic-cad')", max_length=100, unique=True, verbose_name='URL-адрес'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Характеристика'),
        ),
    ]
